haiwen/seahub

- thirdpart/shibboleth/app_settings.py
- thirdpart/shibboleth/middleware.py
Environment variable for shibboleth user name should  be configurable. The default is REMOTE_USER which is provided by e.g. apache modules. Using a different variable the value can be changed, e.g. a Domain can be added or replaced or a different field can be used as a primary key. 
This allows to use other authentication modules for Apache, like Kerberos or CAS which don't necessarily provide a username in the right format (xxx@yyy.com). 
Tested using LemonLDAP::NG Single-Sign-On.
> Shibboleth variable should be configurable. 

- pytest.ini
- seahub/api2/urls.py
- seahub/api2/utils.py
- seahub/api2/views.py
- seahub/api2/views_auth.py
- tests/api/apitestbase.py
- tests/api/test_auth.py
- tests/api/test_repos.py
- tests/api/urls.py
- tests/common/common.py
- tests/install-deps.sh
- tests/seahubtests.sh
Added new apis:
- Logout a client: `/logout-device/`. If the device is a desktop client, also remove all the sync tokens used on that client.
- Generate sync tokens for a list repos: `repo-tokens`. This is used when the user logs in the account again in the client.
Related:
- haiwen/seafile-client#476
- haiwen/seafile#1112
> [api] support logging out an accout from seafile clients

- seahub/templates/registration/login.html
- seahub/views/__init__.py
Use the next parameter for shibboleth, just like for the normal login button.
> Redirect using "next" parameter when using shibboleth button

- seahub/notifications/management/commands/send_notices.py
- seahub/notifications/models.py
- seahub/views/__init__.py
- seahub/views/ajax.py
- seahub/views/file.py
- seahub/wiki/utils.py
- tests/seahub/share/views/test_list_priv_shared_folders.py
When reversing URLs, Django didn't apply urlquote() to arguments before interpolating them in URL patterns. This bug is fixed in Django 1.6. If you worked around this bug by applying URL quoting before passing arguments to reverse(), this may result in double-quoting. If this happens, simply remove the URL quoting from your code.
> remove urlquote when reverse

- .gitignore
- README.markdown
Using a virtualenv is much better than globally installing all of the
project's dependencies, as it doesn't pollute the global package space,
and allows us to work just within the project folder.
> Add instructions for how to set up in a virtualenv

- seahub/views/file.py
According to https://api.onlyoffice.com/editors/config/document, the key
should be changed when document is edited *and* saved. Using a different
key each time the document is opened tells document server a different version
of the file is edited and thus breaks save operations as well as collaborative
editing.
Use obj_id as key since it's a file content based uuid.
> [onlyoffice] Fix document key

- seahub/api2/views.py
client still can create encrypted library when server disable ENABLE_ENCRYPTED_LIBRARY
> client create encrypted library

- seahub/invitations/models.py
So that e.g. the accepter can be addressed more directly or different template texts can be used depending on the accepter's domain.
> seahub.invitations: Give more context to template

- seahub/api2/views.py
- seahub/role_permissions/settings.py
- seahub/utils/repo.py
- seahub/views/__init__.py
1. If not enable user role feature OR
haven't configured `storage_ids` option in user role setting:
Return storage info getted from seafile_api.
And always put the default storage as the first item in the returned list.
2. If have configured `storage_ids` option in user role setting:
Only return storage info in `storage_ids`.
Filter out the wrong stotage id(s).
Not change the order of the `storage_ids` list.
> update multi storage backend feature

- seahub/two_factor/templates/two_factor/core/login.html
This enables users to enter the OTP token right after login without manually focusing the single input field.
> Set autofocus in two factor form with single input field

- seahub/api2/endpoints/admin/groups.py
always return `quota` and `parent_group_id` field no matter if is pro
> update admin groups api

- seahub/views/file.py
if an unauthenticated user view a shared file with can edit permission
redirect this user to login page.
> update view shared file

- seahub/group/utils.py
> In group name validation, search for groups rather than get all groups.

- frontend/src/css/review-comments.css
> fix-comments-avatar-bug

- seahub/wopi/views.py
set UserCanNotWriteRelative to false
because new file creation feature is not implemented on wopi host(seahub)
> update wopi check file info endpoint

- frontend/src/css/draft-review.css
Seahub should update seafile-ui.css file. Now we don't use 'import seafile-ui from' method.
> fix-color-f19645

- frontend/src/components/review-list-view/review-comments.js
修复了 newIndex（oldIndex） === 0 的界面不能跳转的 bug。Index 的取值是大于等于 -1 的整数。
> fix-scroll-bug

- seahub/templates/snippets/add_watermark.html
show shared_by in water mark when anonymous user view shared file
> update water mark

- frontend/src/components/dialog/readme-dialog.js
- frontend/src/components/repo-info-bar.js
- frontend/src/css/repo-info-bar.css
修复了下面的问题：
1. 当 readme.md 和 文件标签同时存在时，增加间距。
2. 新增、重命名 readme.md 文件后，界面立即显示图标。
3. readme 对话框打开后，按 ESC 或者单击对话框外部，可以关闭对话框。
4. 代码类名优化。
> [fix] readme.md

- seahub/auth/middleware.py
- seahub/base/accounts.py
- seahub/settings.py
In some cases, applications can trust the proxy to pass HTTP headers to authenticate a user. This allow a simple form of SSO.
I  added this possibility in seahub.
When the `TRUST_PROXY_AUTHTENTICATION` variable is set to `True`, seafile will create a session for user passed in the `Remote-User` HTTP header. The used HTTP header can be modified by setting the `PROXY_AUTH_HEADER` variable.
The code come mostly from the [YunoHost Seafile package](https://github.com/YunoHost-Apps/seafile_ynh/blob/master/sources/patches/x86-64-sso_auth.patch) written by @Josue-T.
As I never used Django, I am not sure that I placed the code at the correct places. I will be happy to make some corrections if needed.
> Add proxy authentification for simple SSO

- frontend/src/app.js
- frontend/src/css/layout.css
- frontend/src/css/toolbar.css
- frontend/src/pages/my-libs/my-libs.js
On mobile devices:
- Don't show side panel when open app page
- Delete side panel close icon
- When side panel is open, the main panel have a grey shadow. Clicking the shadow can close side panel (Using a modal component).
> adjust my library style in mobile

- frontend/src/pages/wiki/main-panel.js
- frontend/src/wiki.js
Close wiki side panel in mobile devices. Add modal when side panel is open. Click modal then side panel close.
> close side panel in mobile

- seahub/api2/views.py
relay_id is used when desktop client syncing repo, but is removed after 7.0.0.
In order to be compatible with the old client, a default value is required.
Length must be 40
> add REPO_DOWNLOAD_INFO_RELAY_ID

- frontend/src/components/common/notification.js
The aria-label of the notification element should be localized strings.
Blind people who are not native speakers of English will not be able to hear localized descriptions using a screen reader.
> The aria-label of the notification element should be localized strings.

- seahub/wopi/utils.py
This replaces a removed method (see https://docs.python.org/3.9/whatsnew/3.9.html#removed-in-python-39 and https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getiterator) with its successor which should be a drop-in replacement (judging from the docs).
As far as I can see this is the only place that needs fixing for full support of python 3.9. In fact, I'm running the current seafile & seahub under 3.9 and noticed this just because I enabled the collabora office integration.
Because the replacement method was there for a long time (since python 3.2 (02/2011), debian wheezy and later has it etc.) there should be minimal risk in changing that.
> Fix wopi/utils.py for python 3.9

- seahub/onlyoffice/utils.py
**text**, **spreadsheet** and **presentation** values for _documentType_ are deprecated since version 6.1.
https://api.onlyoffice.com/editors/config/#documentType
> change documentType since 6.1

- frontend/src/components/pdf-viewer.js
- frontend/src/css/pdf-file-view.css
- media/js/pdf/web/viewer.js
- display a loading icon instead of a blue progress bar in the `#loadingBar`
- added loading icons for pdf pages
> [pdf viewer] improved loading

- seahub/onlyoffice/utils.py
mode must be either 'edit' or 'view'. Prevents auth missing required
parameter editorConfig.mode (since 7.1 version) error when opening a
share link pointing on an office document
See https://forum.seafile.com/t/seafile-9-onlyoffice-7-1-cant-open-publicly-shared-docs/16521
> Fix share links with OnlyOffice 7.1

- seahub/notifications/management/commands/send_notices.py
By setting `to_user = contact_email`, the timestamp `collaborate_last_emailed_time` gets set for the contact email instead of the username, but that is getting used initially for querying the last emailed timestamps. This leads to notification emails getting sent every time the email sending job runs.
This change makes it more in sync with send_file_updates.py, too.
> Fix collaboration notice sending (Closes: #5062)

- scripts/build/build-server.py
Hi, it would be helpful if the new notification server was also packaged by this script (like the go fileserver).
New files copied:
- notification-server
- seafile-monitor.sh
> Update build-server.py to handle Seafile 10.0 notification server

- frontend/src/components/share-link-panel/link-item.js
- frontend/src/components/share-link-panel/link-list.js
* removed the underline for the link when hover on it
* removed the 'edit' icon
* show 'pointer' cursor for the whole link item
* click the link item to visit the link details(into the 'details' panel')
* adjusted width of the columns
> [share dialog] 'share link' panel: redesigned the link items

- seahub/wopi/views.py
This PR will allow Seafile to send the avatar to Collabora Online to that is gets displayed, like this:
See https://sdk.collaboraonline.com/docs/advanced_integration.html#userextrainfo
I have tested this with Seafile `v11.0.0-server` and `master`, against Collabora Online 23.05 (my local development build).
This is a submission on behalf of Collabora Productivity.
> wopi: Send the avatar for collaborative editing

- seahub/api2/endpoints/share_links.py
fix bug when share link file's parent folder no longer exists
> update get share links api

- frontend/src/components/common/notification-popover/index.js
via clicking the bell icon, or via clicking outside'
- in 'dir view', clicking the notice bell icon, clicking the content(dirents) area, the notice popover was not closed
- in other pages, clicking the notice bell icon, the popover was not closed
> [dir view, other pages] fixed problems 'cannot close the notice popover

- seahub/api2/endpoints/admin/logo.py
Conversion of uploaded logo file is to PNG.
PNG only accepts certain modes.
If the original image is not in one of `1, L, LA, I, P, RGB or RGBA data`, conversion fails resulting in 500 response. Cf. https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png
> FIX "cannot write mode CMYK as PNG" error with JPG original in CMYK mode

- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/wiki2/index.js
- frontend/src/pages/wiki2/main-panel.js
- frontend/src/pages/wiki2/side-panel.js
- frontend/src/pages/wiki2/utils/index.js
- frontend/src/pages/wiki2/wiki.css
- seahub/api2/endpoints/wiki2.py
> Revert "Feat wiki editor title seperation"

- frontend/src/components/dialog/lib-settings.js
- frontend/src/components/dialog/lib-settings/lib-history-setting-panel.js
- frontend/src/components/dialog/lib-settings/lib-old-files-auto-del-setting-panel.js
- frontend/src/components/dir-view-mode/dir-others.js
- frontend/src/components/dir-view-mode/dir-views.js
- frontend/src/components/shared-repo-list-view/shared-repo-list-item.js
- frontend/src/css/lib-settings.css
- frontend/src/metadata/components/dialog/metadata-face-recognition-dialog/index.js
- frontend/src/metadata/components/dialog/metadata-status-manage-dialog/index.js
- frontend/src/pages/my-libs/mylib-repo-list-item.js
- frontend/src/pages/my-libs/mylib-repo-menu.js
- frontend/src/utils/text-translation.js
- frontend/src/utils/utils.js
'history', 'auto deletion', 'extended properties', and 'face recognition')
- deleted 'history settings', 'auto deletion setting' in the dropdown menu & context menu of 'my library' & 'department library' items.
- fixed bug in the context menu of 'department library' items.
- deleted the 'more' menu(included 'extended properties' & 'face recognition') for library 'views'.
- click the 'extended properties' prompt in 'views', the new 'settings' dialog will be shown.
> [library] added new 'settings' dialog(includes setting panels for

- frontend/src/components/view-modes.js
- It used 'shift + 1' & 'shift + 2' as shortcuts. That caused problems. when a user input '!' or '@' in an input on the page, the 'view mode' was changed.
- solution: replaced 'shift + 1/2' to 'ctrl/cmd + shift + 1/2'
> ['view mode'] changed the shortcuts to solve the "input !@" problems

- frontend/src/components/dialog/lib-sub-folder-set-group-permission-dialog.js
- frontend/src/components/dialog/lib-sub-folder-set-user-permission-dialog.js
- frontend/src/components/file-chooser/index.js
- added a title, a 'back' icon, and a 'submit' button to the top
- removed the 'cancel' & 'submit' buttons in the bottom
- added gaps above & below the search input
> ['library folder permission' dialog] redesigned the 'add folder' panel

- seahub/auth/views.py
- seahub/base/models.py
- seahub/profile/models.py
- seahub/role_permissions/settings.py
- seahub/role_permissions/utils.py
- seahub/share/models.py
- seahub/utils/licenseparse.py
- seahub/utils/rpc.py
- seahub/utils/star.py
- seahub/views/__init__.py
- seahub/views/file.py
This PR resolves the deprecation warnings of the `logger` library:
```python
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```
It also fixes a few typos along the way.
> Resolve Python Logger warnings
