haiwen/seahub

- seahub/profile/views.py
- seahub/utils/__init__.py
- seahub/views/sysadmin.py
clear web-api/repo-sync token when delete/inactive an user
> [sysadmin] clear token

- media/css/seahub.css
- media/scripts/app/views/dir.js
- seahub/templates/js/dir-op-bar.html
1. hide setting-icon if is not repo owner
2. hide trash-icon if user-perm is 'r'
> update repo setting/trash/history

- locale/ja/LC_MESSAGES/django.po
- seahub/settings.py
*Add Japanese locale
*Add Japanese translation, contributions and sync with transifex 
Signed-off-by: Hiroshi Miura <miurahr@linux.com>
> Add Japanese translation

- seahub/base/templatetags/seahub_tags.py
I implemented the change like I proposed in Ticket haiwen/seafile#1146 .
I am not fluent enough neither in python nor in django to know if we have to do something about Timezones at this point.
The Diff is a little bit confused because I renamed the old Function and inserted a function with the same name. One can see the code more clear in the split view or the file view.
> implement the <time> html5 tag for all times.

- seahub/api2/utils.py
- seahub/api2/views.py
- tests/api/test_repos.py
Conflicts:
seahub/api2/views.py
> [api] Refactor list owned repos, fetch size from repo object

- media/css/seahub.css
- media/scripts/app/models/repo.js
- media/scripts/app/views/add-group-repo.js
- media/scripts/app/views/add-repo.js
- media/scripts/app/views/group-repos.js
- media/scripts/app/views/repo.js
- seahub/api2/views.py
- seahub/group/templates/group/group_info.html
- seahub/templates/js/create-repo.html
- seahub/templates/js/group-repos.html
- seahub/templates/js/organization-repo.html
- seahub/templates/js/repo.html
- seahub/templates/js/shared-repo.html
- seahub/templates/js/sub-lib.html
- seahub/templates/myhome.html
- seahub/templates/pubrepo.html
* removed 'description', added 'size'
* bugfix
> [libs] modified ui of 'lib list' & 'lib create'

- seahub/api2/authentication.py
- seahub/api2/urls.py
- seahub/api2/views_auth.py
- seahub/base/context_processors.py
- seahub/base/models.py
- seahub/base/sudo_mode.py
- seahub/urls.py
- seahub/utils/__init__.py
- seahub/views/__init__.py
- tests/api/test_auth.py
- tests/api/urls.py
- New table: `base.ClientLoginToken`
- New api endpiont: `/api2/client-login/`, for generating the login token
- New view: `/client-login/`, for checking the token and logging in the session
> support logging in from desktop client directly

- media/css/seahub.css
- seahub/templates/libraries.html
- static/scripts/app/views/group.js
- static/scripts/app/views/myhome-repos.js
- static/scripts/app/views/myhome-shared-repos.js
- static/scripts/app/views/myhome-sub-repos.js
- static/scripts/app/views/organization.js
Conflicts:
static/scripts/app/views/group.js
static/scripts/app/views/myhome-repos.js
static/scripts/app/views/myhome-shared-repos.js
static/scripts/app/views/organization.js
> enable 'show error' for 'fetch libs'

- seahub/api2/views.py
do not return sub-repo info if sub-repo is not enabled
> [api] update repos view

- seahub/views/ajax.py
- static/scripts/app/views/dirent.js
when operate a dir/file, use their own perm instead of repo perm
> [folder-perm] update perm check

- seahub/notifications/views.py
add try-exception when load notice detail to json
> [notice] update code

- seahub/notifications/models.py
use "Deleted Library" as repo-name if a repo is deleted
> [notice] update notice msg

- seahub/api2/views.py
only staff user or group member can get group repos in pub group
> [group repos] update permisson check

- media/css/doc_and_pdf.css
- media/js/pdf2html.js
- seahub/api2/urls.py
- seahub/api2/views.py
- seahub/templates/shared_file_view.html
- seahub/templates/snippets/file_view_js.html
- seahub/templates/snippets/office_convert_html.html
- seahub/templates/snippets/office_convert_js.html
- seahub/templates/snippets/office_convert_style.html
- seahub/templates/snippets/spreadsheet_convert_js.html
- seahub/templates/view_file_base.html
- seahub/templates/view_file_document.html
- seahub/templates/view_file_pdf.html
- seahub/templates/view_history_file.html
- seahub/urls.py
- seahub/utils/__init__.py
- seahub/views/file.py
> Revert "improve office preview"

- seahub/utils/__init__.py
- seahub/views/file.py
* view open documents files with libreoffice convertor in pro edition
* fixed fetching embedded images when viewing xls files
> several improvements to office preview

- seahub/views/__init__.py
Reduce unnecessary database reads.
> improve the performance of check_repo_access_permission

- seahub/api2/urls.py
- seahub/api2/views.py
- seahub/share/models.py
- tests/api/test_shares.py
1. generate upload shared link
2. delete upload shared link
3. set password/expire when generate a shared download/upload link
4. list direnty in shared dir download link
5. password check if file/dir share is encrypted
> [web-api] update share link api

- seahub/templates/snippets/office_convert_js.html
- seahub/templates/snippets/spreadsheet_convert_js.html
- seahub/urls.py
- seahub/utils/__init__.py
- seahub/utils/http.py
- seahub/views/file.py
It follows the security model of serving image thumbnails.
> improve office preview permission check

- seahub/templates/sysadmin/userinfo.html
remove desc & add size and last update
> update sysadmin user info page

- seahub/templates/base.html
- seahub/templates/registration/login.html
- seahub/templates/registration/logout.html
- seahub/templates/registration/password_reset_complete.html
- seahub/templates/registration/password_reset_confirm.html
- seahub/templates/registration/password_reset_done.html
- seahub/templates/registration/password_reset_form.html
- seahub/templates/registration/registration_complete.html
- seahub/templates/registration/registration_form.html
- seahub/templates/share_access_validation.html
- seahub/templates/shared_file_view.html
- seahub/templates/view_shared_dir.html
- seahub/templates/view_shared_upload_link.html
- do not show 'nav' for these pages
- show 'lang' for non-logged-in users
> modified 'header' for some pages

- media/css/seahub.css
- seahub/templates/view_file_base.html
- seahub/templates/view_file_markdown.html
- seahub/templates/view_file_text.html
- seahub/templates/view_history_file.html
> new btn link

- seahub/base/context_processors.py
- seahub/settings.py
- seahub/templates/js/templates.html
- seahub/templates/libraries.html
- static/scripts/app/views/share.js
在settings.py里面添加了一个用于控制分享链接密码最小长度的选项：
SHARE_LINK_PASSWORD_MIN_LENGTH = 8 
还有一些对相关文件的修改
> fix a bug about generating random passwords

- seahub/templates/js/templates.html
> give permission more space

- media/css/seahub.css
- seahub/templates/sysadmin/sys_useradmin.html
- seahub/templates/sysadmin/useradmin_js.html
跟之前的random-password差不多，关于random password的css和以前的也一样，去掉了id选择器，不知道是否可以把它们放在seahub.css前面，作为通用的随机密码css.
> generate a random password when adding a user

- seahub/api2/views.py
- seahub/templates/view_file_base.html
- seahub/templates/view_file_markdown.html
- seahub/templates/view_file_text.html
- seahub/views/file.py
check folder perm instead of repo perm when operate dir
> update permission check

- seahub/api2/views.py
check permission and file id before star/unstar a file
> [file-star-api] update file star api

- seahub/api2/views.py
- tests/api/apitestbase.py
- tests/api/test_repos.py
Depends on:
- seafile PR: https://github.com/haiwen/seafile/pull/1359
- seafile-client PR: https://github.com/haiwen/seafile-client/pull/706
> create repo api: accept magic and random_key generated on client side

- seahub/api2/views.py
- seahub/group/forms.py
- seahub/group/utils.py
- seahub/group/views.py
- tests/api/test_groups.py
- tests/seahub/group/views/test_group.py
can only contain letters, numbers, blank, hyphen or underscore
> [web/api] update group name validation check

- seahub/views/sysadmin.py
show owned/shared-in repos at user info page
> [sysadmin] update user info page

- seahub/api2/views.py
- tests/api/test_files.py
add 'reuse' argument to control if reuse fileserver access token
> [web-api] update download file api

- seahub/views/ajax.py
> Revert "check folder permission before set user/group perm"

- media/js/base.js
- seahub/notifications/templates/notifications/user_notification_list.html
- seahub/share/templates/share/links.html
- seahub/share/urls.py
- seahub/share/views.py
- seahub/templates/repo.html
- seahub/templates/repo_shared_link.html
- seahub/templates/snippets/repo_dir_data.html
- seahub/templates/snippets/shared_link_js.html
- seahub/templates/view_file_base.html
- seahub/views/__init__.py
- seahub/views/ajax.py
- static/scripts/app/views/dirent.js
- static/scripts/app/views/organization-repo.js
- static/scripts/app/views/shared-repo.js
- static/scripts/common.js
> use 'POST' instead of 'GET' for some requests

- seahub/templates/sysadmin/userinfo.html
> enable sysadmin transfer user's repo

- seahub/api2/views.py
- tests/api/test_search_user.py
1. not return unregistered user
2. add arg to control if return myself
> [api] update search user api

- seahub/api2/endpoints/dir_shared_items.py
- tests/api/endpoints/test_dir_shared_items.py
1. update perm check when share repo/dir
2. check if user registered when share repo/dir
> [api] update share dir item api

- seahub/templates/view_shared_dir.html
> add "Last Update" for shared links

- seahub/templates/repo.html
- seahub/views/__init__.py
> Revert "use "view_lib_file" instead of "view_repo_file""

- seahub/api2/views.py
- tests/api/test_repo_history_limit.py
still can get limit days if history limit setting not enabled
> [api2] update repo history limit

- static/scripts/app/views/dir.js
remember sort mode when view different folder
> update sort dirents

- tests/api/test_search_user.py
Added test for searching by contact_email.
Please merge.
> Extended test of user search

- seahub/api2/endpoints/send_share_link_email.py
- seahub/api2/endpoints/send_upload_link_email.py
- seahub/share/views.py
- tests/api/endpoints/test_send_share_link.py
- tests/api/endpoints/test_send_upload_link.py
- tests/seahub/share/views/test_send_shared_link.py
- tests/seahub/share/views/test_send_shared_upload_link.py
support contact_email as from and in Reply-to header.
Apart from that I improved the share-link tests in b64e882.
> Support contact_email in email sending

- seahub/base/database_storage/database_storage.py
The following transaction management APIs will be removed:
the functions commit_unless_managed and rollback_unless_managed
https://github.com/django-nose/django-nose/pull/207/files
https://github.com/mocco/django-fabric/pull/17/files
> Replaces commit_unless_managed with atomic transaction

- seahub/templates/js/templates.html
- static/scripts/app/views/widgets/hl-item-view.js
Show operation icons when the item get focus.
> Accessibility improvement

- static/scripts/app/views/dir.js
when visit a invalid repo dir page, error msg will show.
but then visit a valid repo, error msg still there and no dir page show.
> update dir page

- seahub/api2/endpoints/file.py
- tests/api/endpoints/test_dir_view.py
- tests/api/endpoints/test_file_view.py
1. return checked file name when creat a new file
2. update test
> update file api

- seahub/api2/endpoints/dir_shared_items.py
- seahub/api2/views.py
- seahub/views/sysadmin.py
- tests/api/test_repo_owner.py
1. reshare repo after user/admin transfer repo
2. show org repo share out list at share popup in org mode
> update repo share

- seahub/templates/base_for_backbone.html
allow user change welcome message by change SITE_NAME setting
> update welcome message

- seahub/__init__.py
allow user define repo created callback func at ../conf/seahub_settings.py
> repo created callback

- seahub/templates/registration/password_reset_email.html
My idea was only to set 
```
</p>
<p>
<a href="{{ url_base }}{% url 'auth_password_reset_confirm' uidb36=uid token=token %}">{% trans "Reset Password" %}</a>
</p>
```
> Reset PWD - Looks like better

- seahub/templates/registration/activation_email.html
Sending the registration link as real clickable link
> Activation: link as link not Text

- seahub/views/ajax.py
check if is cloud_mode before use `seafile_api.is_inner_pub_repo()`
> update cloude mode check

- seahub/api2/endpoints/account.py
- seahub/forms.py
- seahub/profile/forms.py
> update translate string

- seahub/api2/endpoints/account.py
- tests/api/endpoints/test_account.py
remove 'note' releated operation
> update account api

- seahub/api2/views.py
- tests/api/test_repo_group_folder_perm.py
- tests/api/test_repo_user_folder_perm.py
not check path existence when delete user/group folder permission
> update remove folder permission

- seahub/templates/sysadmin/sys_useradmin.html
- seahub/views/sysadmin.py
- tests/seahub/views/sysadmin/batch_add_user.csv
1. if user exists, only update the user's optional info
2. if NOT exists, create user first, then update the user's optional info
> update admin import user

- seahub/api2/endpoints/search_user.py
- tests/api/endpoints/test_search_user.py
user can search if he/she has no permission of using global address book
> update search user

- seahub/api2/endpoints/shared_folders.py
- seahub/api2/endpoints/shared_repos.py
- seahub/templates/js/templates.html
- tests/api/endpoints/test_shared_folders.py
- tests/api/endpoints/test_shared_repos.py
return contact email when get info of out shared repos/folders
> update api of out shared repos/folders

- seahub/views/sysadmin.py
fix bug when user upload a invalid csv file
> update import users

- seahub/api2/endpoints/admin/libraries.py
for case of `seafile-data` has been damaged
no `repo object` will be returned from seafile api
delete the database record anyway
> update admin delete repo api

- seahub/api2/endpoints/admin/batch_set_user_quota.py
- seahub/urls.py
> admin user batch api

- seahub/group/templates/group/add_member_email.html
- seahub/notifications/management/commands/send_notices.py
- seahub/templates/shared_link_email.html
- seahub/templates/shared_upload_link_email.html
- seahub/templates/sysadmin/user_add_email.html
- seahub/templates/sysadmin/user_batch_add_email.html
translate `ccent-email` to `name` in some sentences
> update email body message

- seahub/api2/endpoints/admin/libraries.py
return repo owner if current repo is an org repo
> update admin get repo info

- seahub/templates/js/templates.html
- seahub/templates/view_shared_dir.html
- seahub/thumbnail/utils.py
- seahub/views/ajax.py
- seahub/views/repo.py
- static/scripts/app/views/dir.js
- static/scripts/app/views/starred-file.js
- static/scripts/common.js
> video thumbnail

- seahub/api2/views.py
return obj info when copy/move file via web api in bulk
> update file ops api

- seahub/views/ajax.py
- seahub/views/sysadmin.py
1. seafile_api.get_org_user_quota_usage
1. seafile_api.get_org_user_quota
> update usage of seafile api

- tests/api/endpoints/test_dir_shared_items.py
test share failed when share the same item to the same user/group
> update dir share item api test

- seahub/templates/base.html
- seahub/templates/view_shared_dir.html
- seahub/views/repo.py
1. always return is_img and is_video info of a file
1. move magnific popup css file to base.html
> update view shared dir page

- seahub/api2/endpoints/repos_batch.py
- seahub/urls.py
- tests/api/endpoints/test_repos_batch.py
batch share repos to user/group
> add v2.1 repos api

- seahub/admin_log/models.py
- seahub/api2/endpoints/admin/libraries.py
- seahub/api2/endpoints/admin/users_batch.py
- seahub/views/sysadmin.py
- static/scripts/sysadmin-app/views/admin-log.js
- tests/api/endpoints/admin/test_logs.py
1. add log when admin create repo
1. add log when admin batch delete user
1. update test
> update admin log

- seahub/api2/views.py
The path separator was missing.
> Fixed the location header after creating directory.

- seahub/wopi/utils.py
- seahub/wopi/views.py
1. use utc timestamp for access_token_ttl
1. return 404 when user/repo/file not found
> update wopi api

- seahub/utils/__init__.py
- tests/seahub/utils/test_normalize_dir_path.py
- tests/seahub/utils/test_normalize_file_path.py
1. Add '/' at the end of directory path if necessary.
1. And make sure path starts with '/'
> normalize file/dir path

- seahub/api2/endpoints/admin/upload_links.py
> admin upload links

- static/scripts/app/views/notifications.js
set 3 * 60 as the default interval for the js value.
> update notification interval

- seahub/api2/endpoints/admin/org_users.py
seafile_api.get_org_quota(org_id)
seafile_api.set_org_user_quota(org_id, email, user_quota)
> update org quota

- seahub/templates/js/templates.html
- seahub/templates/libraries.html
Minor changes to the English in elements of the web interface.
> Minor language changes in web interface

- seahub/api2/views.py
update get quota total/usage of org user
> update account info api

- seahub/api2/endpoints/admin/org_users.py
- seahub/auth/forms.py
- seahub/base/accounts.py
- seahub/institutions/views.py
- seahub/views/sysadmin.py
- tests/api/endpoints/test_account.py
clear token when inactive user, delete user, change user password
> update clear token

- tests/seahub/thirdpart/shibboleth/test_middleware.py
- thirdpart/shibboleth/middleware.py
https://forum.seafile.com/t/shibboleth-affiliation-and-multi-institution/2036
> [shibboleth] Add joker * in affiliation role map

- seahub/views/sysadmin.py
Optimize database query when get user's name and contact email
> admin export users to excel

- seahub/base/management/commands/export_users.py
export users to '../users.xlsx'.
> python manage.py export_users

- seahub/api2/endpoints/admin/account.py
- seahub/api2/endpoints/search_user.py
- seahub/api2/endpoints/user.py
- seahub/api2/urls.py
- seahub/profile/models.py
- seahub/profile/templates/profile/set_profile.html
- seahub/profile/views.py
- seahub/settings.py
- seahub/urls.py
- tests/api/endpoints/admin/test_account.py
- tests/api/endpoints/test_search_user.py
- tests/api/endpoints/test_user.py
enable user to choose if show himself in global address book
> add ENABLE_ADDRESSBOOK_OPT_IN setting

- seahub/api2/endpoints/file.py
use `new_file_path` when create office file from offie template
> update create file api

- seahub/api2/endpoints/admin/group_members.py
Not check if user exist when remove a group member
> update admin group memeber api

- seahub/templates/snippets/spreadsheet_convert_js.html
fix bug when file name contains '&'
> file shared link

- seahub/api2/views.py
search file in 'all', 'mine', 'shared', 'group', 'public' repos
> update search file api

- seahub/api2/endpoints/copy_move_task.py
- seahub/api2/endpoints/file.py
- seahub/api2/views.py
- seahub/templates/js/templates.html
- seahub/utils/file_op.py
- seahub/utils/repo.py
- seahub/views/__init__.py
- seahub/views/ajax.py
- seahub/views/file.py
- seahub/wopi/views.py
- static/scripts/app/views/dir.js
- static/scripts/app/views/dirent.js
Don't allow delete/rename/move a file when it is locked
> update lock feature

- seahub/api2/views.py
filter out None permission files
> update file search result

- seahub/wopi/views.py
add log for HTTP_X_WOPI_OVERRIDE
add log for HTTP_X_WOPI_LOCK
add log for HTTP_X_WOPI_OLDLOCK
> add some log for view office file via OOS

- seahub/group/views.py
- seahub/views/wiki.py
fix storage id related bug when create personal/group wiki
> create personal/group wiki

- seahub/utils/__init__.py
- seahub/wopi/views.py
use inner fileserver update url when save a file via WOPI
> update wopi post file content

- seahub/api2/endpoints/share_link_zip_task.py
- seahub/api2/endpoints/upload_links.py
- seahub/views/ajax.py
- seahub/views/file.py
- seahub/views/repo.py
- tests/api/endpoints/test_upload_links.py
add repo access permission check for share link creator
> update permission when user download/upload link

- seahub/api2/endpoints/admin/library_dirents.py
return `dst_obj_name` field for case of src file/folder been renamed.
> update admin library dirent copy api

- seahub/api2/views.py
- seahub/settings.py
- seahub/templates/js/templates.html
- seahub/templates/libraries.html
- seahub/utils/repo.py
- seahub/views/__init__.py
add STORAGE_CLASS_MAPPING_POLICY setting
> update multi storage backend feature

- seahub/api2/endpoints/dir.py
- seahub/api2/views.py
- tests/api/test_files.py
return file info when get dir info recursively
> update dir view

- seahub/api2/endpoints/dir.py
- seahub/api2/views.py
> update get dir/file info api

- seahub/api2/views.py
recreate dir when failed when `file already exists'.
> update create dir api

- media/assets/scripts/app/views/folder-perm.js
- media/assets/scripts/app/views/share.js
- seahub/api2/endpoints/shareable_groups.py
- seahub/templates/libraries.html
- seahub/views/__init__.py
- static/scripts/app/views/dialogs/repo-folder-perm-admin.js
- static/scripts/app/views/folder-perm.js
- static/scripts/app/views/share.js
1. share library/folder
2. set folder permission
> filter out address book gorup when:

- seahub/templates/js/sysadmin-templates.html
* [libraries] don't show owner for group owned library, and etc.
* [groups] don't show owner and operations for address book group.
> [system admin] modification

- seahub/api2/endpoints/search_user.py
disable full email searh if current user is a guest user
> update search user api

- seahub/api2/endpoints/address_book/groups.py
- seahub/api2/endpoints/address_book/members.py
- seahub/api2/endpoints/admin/account.py
- seahub/api2/endpoints/admin/address_book/groups.py
- seahub/api2/endpoints/admin/group_members.py
- seahub/api2/endpoints/admin/group_owned_libraries.py
- seahub/api2/endpoints/admin/libraries.py
- seahub/api2/endpoints/dir_shared_items.py
- seahub/api2/endpoints/group_members.py
- seahub/api2/endpoints/group_owned_libraries.py
- seahub/api2/endpoints/groups.py
- seahub/api2/endpoints/repos_batch.py
- seahub/api2/permissions.py
- seahub/api2/utils.py
- seahub/api2/views.py
- seahub/group/utils.py
- seahub/group/views.py
- seahub/test_utils.py
- seahub/urls.py
- seahub/views/ajax.py
get/add/modify/delete user/group folder permission
> update group owned library folder permission

- seahub/base/templatetags/seahub_tags.py
> show repo's first commit's desc

- seahub/api2/endpoints/admin/trash_libraries.py
check if repo exists in trash.
> update admin restore deleted repo api

- seahub/views/file.py
use origin repo_id/file_path if current repo is a virtual repo
> update onlyoffice view file

- seahub/api2/endpoints/repos_batch.py
- seahub/api2/views.py
remove pro version check when create folder with parents
> update repos dir api

- seahub/api2/endpoints/admin/organizations.py
- seahub/api2/views.py
- seahub/urls.py
- seahub/views/sysadmin.py
1, get org info
2, update name/max user number/quota
3, delete an org
> add admin org api

- media/css/seahub.css
User profile form label fix for Hungarian language.
> User profile form fix

- seahub/templates/view_shared_upload_link.html
- seahub/views/ajax.py
> [fix]the email reminds unread notifications after uploading file

- seahub/views/ajax.py
optimize get file type and thumbnail
> update ajax list lib dir

- seahub/api2/views.py
add share_from(name/contact_email) field when get group/public repos
> update api2/repos api

- seahub/api2/views.py
> update file detail api

- seahub/api2/endpoints/shared_repos.py
do not remove share if user/group not found
> update shared out repos api

- seahub/api2/endpoints/dir_shared_items.py
optimize share repo to multi users
> update dir-share-item api

- seahub/api2/endpoints/admin/file.py
rm get file upload info code which is only used by icourt
> update admin file detail api

- media/css/seahub.css
- media/css/spreadsheet_convert.css
- seahub/templates/js/templates.html
- seahub/templates/snippets/shared_link_js.html
- seahub/templates/view_file_base.html
- static/scripts/app/views/dirent.js
- static/scripts/app/views/repo.js
first : modify the editor to be resposed for pc and mobile;
second: change the editor menu style for different device;
> repair editor menu style for different device

- seahub/templates/js/sysadmin-templates.html
- seahub/views/sysadmin.py
show expire days according to seafile.conf configuration
> update admin libraries trash page

- seahub/api2/endpoints/copy_move_task.py
- seahub/api2/endpoints/file.py
- seahub/api2/views.py
- seahub/views/ajax.py
- static/scripts/app/views/dialogs/dirent-mvcp.js
- static/scripts/app/views/dir.js
- static/scripts/app/views/dirent-grid.js
- static/scripts/app/views/dirent.js
remove same repo_id,path check when copy dirent
> update copy dirent api

- seahub/templates/js/templates.html
- static/scripts/app/views/dir.js
- static/scripts/app/views/dirent-grid.js
- static/scripts/app/views/dirent.js
if current user has 'is_admin' library permssion, show folder share icon
> update logic of show folder share icon

- seahub/base/accounts.py
check IS_EMAIL_CONFIGURED settings when get can_send_share_link_mail role permission
> update user role

- seahub/templates/view_file_base.html
- seahub/views/file.py
always show error msg if can NOT view file online
> update file view page

- seahub/templates/js/templates.html
- seahub/templates/snippets/file_share_popup.html
- seahub/templates/sysadmin/sys_publink_admin.html
- seahub/templates/sysadmin/sys_upload_link_admin.html
- seahub/views/ajax.py
- seahub/views/file.py
- static/scripts/app/views/dirent-grid.js
- static/scripts/app/views/dirent.js
- static/scripts/app/views/share.js
add can_preview field for file when ajax list lib dir
hide preview-only permission if a file can not preview
> update share link permission

- seahub/api2/endpoints/smart_link.py
> update smart link api

- seahub/templates/snippets/add_watermark.html
add site name before user name when show water mark
> update water mark

- tests/seahub/views/file/test_view_lib_file.py
This reverts commit 6f51aec1ccc74b877d7f8b6aa100aead0d12edfe.
> Revert "[tests] Update view_lib_file"

- static/scripts/app/views/dir.js
> Revert "[dir view] getMore: fixup for some cases"

- seahub/templates/libraries.html
- seahub/views/__init__.py
show expire days according to seafile.conf configuration
> update common user's deleted libraries page

- seahub/views/ajax.py
fix bug when copy directory its subdirectory
> update ajax multi copy dirents

- seahub/api2/endpoints/file_history.py
remove unused paginator links header
> update file history api

- seahub/role_permissions/settings.py
set custom(not default and guest) role's permission to False
if not configured in seahub_settings.py
> update role permission

- seahub/share/decorators.py
- seahub/views/file.py
- seahub/views/repo.py
use SHARE_LINK_LOGIN_REQUIRED to control both preview and edit share link
> update view shared file/folder

- seahub/api2/endpoints/group_owned_libraries.py
- seahub/api2/views.py
- seahub/urls.py
return 'group_name' field if current library is a group owned library
> update api of shared with me

- seahub/api2/endpoints/file.py
- seahub/views/ajax.py
user has rw permission can unlock file locked by OnlineLock
> update lock file

- requirements.txt
- tests/api/test_ping.py
ref: https://forum.seafile.com/t/6-3-6-pro-api-broken-user-feedback-as-i-go/7356/5
> Upgrade rest_framework to 3.3.3 to fix html render error in web api

- seahub/api2/endpoints/shared_repos.py
> update shared repos api

- seahub/onlyoffice/settings.py
- seahub/onlyoffice/utils.py
- seahub/templates/view_file_onlyoffice.html
This reverts commit f6a12786d137da43938f4b2e07bf95fba764255d.
> Revert "update onlyoffice edit file (#2338)"

- seahub/onlyoffice/views.py
- seahub/wopi/views.py
transfer online_office_update to seafile api when get fileserver access token
> update OOS/OnlineOffice update file

- frontend/src/draft-review.js
Change button-title and add tooltip for publish draft button.
> add-tooltip

- seahub/api2/endpoints/repos.py
use group_name as owner_name if current repo is a group owner repo
> update get shared repos api

- frontend/src/components/review-list-view/review-comments.js
- frontend/src/css/draft-review.css
- frontend/src/css/review-comments.css
- frontend/src/draft-review.js
- frontend/src/models/review-comment.js
Select texts then add comment button in draft.
> Add draft comment button

- seahub/api2/endpoints/repos.py
return storage_id and storage_name field
> update get mine repos api

- frontend/src/components/review-list-view/review-comment-dialog.js
- frontend/src/components/review-list-view/review-comments.js
- frontend/src/css/draft-review.css
- frontend/src/draft-review.js
Change getting selected text method and delete some useless codes in review-comment component.
> change selection

- frontend/src/draft-review.js
Use map API in List Object instead of the original for loop.
> fix-fragment-nodes-bug

- seahub/api2/endpoints/group_libraries.py
- seahub/api2/endpoints/groups.py
> update get group repos api

- frontend/src/components/review-list-view/review-comment-dialog.js
- frontend/src/css/review-comment-dialog.css
- frontend/src/css/review-comments.css
- frontend/src/draft-review.js
Fix some bugs in comment dialog.
1. adjust text-area box-shadow（from 5px #aaa to 3px #ccc）
2. adjust text-area width（500px）
3. fix-bug: if there is a quoteblock in comment, adjust style.
> fix-comment-dialog-bug

- frontend/src/css/review-comment-dialog.css
- frontend/src/draft-review.js
1. Make sure that range is right and common after we clicked add-comment button.
2. Remove null nodes in fragment if we select several paragraphs.
> fix-selection

- frontend/src/components/dialog/create-group-dialog.js
- frontend/src/components/toolbar/groups-toolbar.js
- frontend/src/pages/groups/groups-view.js
> fix-create-group

- seahub/utils/__init__.py
- tests/seahub/utils/test_generate_file_audit_event_type.py
update get file audit event type/device
> get file audit event type/device

- seahub/templates/js/templates.html
- seahub/templates/sysadmin/sys_publink_admin.html
> update trans str

- seahub/profile/forms.py
- seahub/profile/templates/profile/set_profile.html
- seahub/profile/views.py
- seahub/settings.py
add ENABLE_DELETE_ACCOUNT and ENABLE_UPDATE_USER_INFO settings
> update user profile page

- seahub/api2/endpoints/repos.py
send user login msg when user get repos
> update v2.1 repos api

- frontend/src/draft-review.js
Fix draft selection bug when users select side panel.
> fix-selection-bug

- frontend/src/components/dialog/list-related-file-dialog.js
- frontend/src/markdown-editor.js
Add repo name in list-related-file dialog.
> Add repo name

- frontend/src/components/dialog/rename-group-dialog.js
- frontend/src/css/manage-members-dialog.css
- frontend/src/pages/groups/group-view.js
Fix style bug in group dialogs.
> fix-style-bug

- frontend/src/components/dialog/add-related-file-dialog.js
- frontend/src/components/dirent-detail/detail-list-view.js
- frontend/src/css/dirent-detail.css
- frontend/src/css/file-chooser.css
Add subtitle in related-file dialog.
Adjust style.
> Add-subtitle

- seahub/api2/views.py
- seahub/utils/__init__.py
root, desc, magic, enc_version, repaired and random_key
> remove unused filed

- frontend/src/pages/dashboard/files-activities.js
- seahub/api2/endpoints/activities.py
parameter, size -> avatar_size
field of response, time_relative -> time
> update activities api

- frontend/src/css/shared-file-view.css
- frontend/src/shared-file-view-markdown.js
fix-shared-markdown-file-style
> fix-shared-markdown-file

- frontend/src/components/dialog/add-related-file-dialog.js
- frontend/src/components/dialog/list-related-file-dialog.js
1. Use mtime_relative instead of mtime.
2. Add onRepoItemClick function to deal with click repo item.
> fix-related-file-bug

- frontend/src/components/dialog/manage-members-dialog.js
- frontend/src/css/manage-members-dialog.css
- frontend/src/models/user-select.js
Fix adding multi group members bug.
> [group-member] add-multi-members

- seahub/api2/endpoints/dir.py
- seahub/templates/js/templates.html
- static/scripts/app/views/dirent-details.js
- tests/api/endpoints/test_dir_view.py
remove file_count, dir_count and size field
> update dir detail

- seahub/api2/endpoints/dir.py
- tests/api/endpoints/test_dir_view.py
> update v2.1 dir api

- seahub/api2/utils.py
> update starred file api

- frontend/src/components/repo-info-bar.js
Click edit button in readme dialog, then page skip to rich markdown editor directly.
> [fix] edit-mode

- seahub/api2/endpoints/repo_set_password.py
use request.data to get paramerer from POST and PUT request
https://www.django-rest-framework.org/tutorial/2-requests-and-responses/
request.POST  # Only handles form data.  Only works for 'POST' method.
request.data  # Handles arbitrary data.  Works for 'POST', 'PUT' and 'PATCH' methods.
> update set repo password api

- frontend/src/components/dialog/manage-members-dialog.js
- frontend/src/shared-file-view-text.js
Fix warning in shared txt file viewer.
> fix warnings

- frontend/src/components/comments-list.js
- frontend/src/css/comments-list.css
- frontend/src/css/view-file-text.css
- frontend/src/view-file-text.js
Add comment function in text view page.
> [update] txt-view-comment

- frontend/src/components/dialog/add-related-file-dialog.js
- frontend/src/components/dialog/copy-dirent-dialog.js
- frontend/src/components/dialog/move-dirent-dialog.js
- frontend/src/components/dialog/save-shared-file-dialog.js
- frontend/src/components/file-chooser/file-chooser.js
- frontend/src/shared-file-view-text.js
1. 修复文件大小是 0 时，按钮显示 NaN.
2. 修复文件另存为对话框 Save to。
3. 增加文件选择组件（file-chooser）不同模式。
> [fix] shared text

- frontend/src/pages/share-admin/share-links.js
> [update] external link dialog

- frontend/src/css/files-activities.css
- frontend/src/pages/dashboard/files-activities.js
- frontend/src/view-file-text.js
1. Delete top border in file activities page.
2. When text file is error, forbid to use edit button.
> [fix] fix activities UI and text edit button

- frontend/src/components/user-select.js
1. Fix gettext method.
2. Fix User not found.
> Fix user select component

- frontend/src/markdown-editor.js
Fix getCommentsNumber function parameters for markdown viewer page.
Add this.userName for comment dialog.
> [Add] comment

- seahub/api2/views.py
return org info instead of 'success'
> update admin create org api

- seahub/api2/endpoints/starred_items.py
always keep starred repos in front of response list
> update sort logic of starred items

- frontend/src/components/dir-view-mode/dir-column-nav.js
- frontend/src/components/dir-view-mode/dir-column-view.js
- frontend/src/components/dir-view-mode/dir-grid-view.js
- frontend/src/css/lib-content-view.css
In wiki mode, user can adjust column and resize width. Then save it in cookie.
> [add] column resize

- seahub/base/models.py
filter out starred repo/folder
> update old starred files api

- frontend/src/components/dir-view-mode/dir-column-view.js
- frontend/src/css/lib-content-view.css
Change wiki nav maximal width to 40%.
> fix resize strip

- frontend/src/components/dir-view-mode/dir-column-view.js
- frontend/src/css/lib-content-view.css
When component will mount, browser should check cookie then set page width.
> fix resize width

- frontend/src/view-file-text.js
- seahub/templates/image_file_view_react.html
- seahub/templates/text_file_view_react.html
- seahub/templates/video_file_view_react.html
- seahub/templates/xmind_file_view_react.html
* for 'text file view': fixed 'bottom blank' problem; added 'line number' back
> [file view] modification: make css file in <head> instead of bottom

- frontend/src/css/lib-content-view.css
> Revert "update file view padding"

- frontend/src/css/files-activities.css
- frontend/src/pages/dashboard/files-activities.js
> Revert "activity op color"

- frontend/src/components/toolbar/mutilple-dir-operation-toolbar.js
- frontend/src/pages/lib-content-view/lib-content-container.js
- frontend/src/pages/lib-content-view/lib-content-view.js
1. When selected a file and open file detail panel, then selected another file, the detail panel is the first file information.
2. When close file detail panel and unselect this file, this page can't work.
3. Fix some warnings(parameters validation).
> Selected file detail panel

- frontend/src/components/file-view/comment-panel.js
- frontend/src/draft.js
- frontend/src/markdown-editor.js
Fix bugs:
1. FindRange function need editor parameter rather than value parameter, because slate updated to new version.
2. Fix: In MarkdownViewerSlate page,  the right comment panel can't refresh automatically after we use comment-dialog component to add a comment.
> update codes for slate

- frontend/src/components/dialog/insert-file-dialog.js
- frontend/src/markdown-editor.js
> Delete texts in insert file dialog

- frontend/src/components/file-view/file-view.js
- frontend/src/view-file-audio.js
- frontend/src/view-file-document.js
- frontend/src/view-file-image.js
- frontend/src/view-file-pdf.js
- frontend/src/view-file-spreadsheet.js
- frontend/src/view-file-svg.js
- frontend/src/view-file-text.js
- frontend/src/view-file-unknown.js
- frontend/src/view-file-video.js
- frontend/src/view-file-xmind.js
* added component 'file-view.js'
> [file view] code improvement

- frontend/src/components/shared-file-view/shared-file-view-tip.js
- frontend/src/components/shared-file-view/shared-file-view.js
- frontend/src/css/shared-file-view.css
- frontend/src/shared-file-view-image.js
- frontend/src/shared-file-view-markdown.js
- frontend/src/shared-file-view-pdf.js
- frontend/src/shared-file-view-text.js
- seahub/templates/shared_file_view_react.html
* added component shared-file-view.js & shared-file-view-tip.js
* modified 'text file view'
> [shared file view] code improvement

- seahub/api2/endpoints/share_links.py
return encoded_thumbnail_src field
> update share link dirent api

- frontend/src/components/dirent-detail/detail-list-view.js
- frontend/src/components/dirent-detail/dirent-details.js
- frontend/src/components/toolbar/view-mode-toolbar.js
- frontend/src/css/dirent-detail.css
- frontend/src/css/layout.css
- frontend/src/css/toolbar.css
- frontend/src/pages/lib-content-view/lib-content-container.js
- frontend/src/pages/lib-content-view/lib-content-toolbar.js
- frontend/src/pages/lib-content-view/lib-content-view.js
Add detail panel button at toolbar.
> Detail panel

- seahub/api2/endpoints/notifications.py
- tests/api/endpoints/test_notifications.py
fix bug for resource check, add argument check
> fix bug of user notification

- seahub/base/accounts.py
- tests/api/endpoints/test_shared_repos.py
- tests/api/test_public_repo.py
- tests/api/test_shared_repo.py
- tests/seahub/base/test_accounts.py
- tests/seahub/views/init/test_libraries.py
can add public repo permission update to
both "can_add_public_repo" and "ENABLE_USER_CREATE_ORG_REPO"
> can add public repo permission update

- frontend/src/components/toolbar/markdown-viewer-toolbar.js
- frontend/src/markdown-editor.js
"Auto save draft" information should appear at FileInfo Component.
> fix auto save draft

- frontend/src/markdown-editor.js
- seahub/api2/views.py
When user's permission is 'cloud-edit', user can edit this file in markdown editor.
> Fix edit file permission

- frontend/src/components/file-view/file-toolbar.js
- frontend/src/components/file-view/file-view.js
- frontend/src/view-file-text.js
> Revert "Update txt file save mechanism"

- frontend/src/components/dialog/create-tag-dialog.js
1、When tag name is vacant, submit button is disabled.
2、Fix onRepoTagCreated function is undefined situation.
3、Deal with new tag name is invalid( response state is 400 or 500).
> fix tag error

- seahub/templates/sysadmin/settings.html
> Revert "sysadmin enable user create org repo update description"

- seahub/wopi/views.py
return last modified time field
> update wopi file info api

- frontend/src/components/index-viewer.js
- frontend/src/css/index-viewer.css
Deal with special situations in published wiki page:
1. list item is a link node, render it to a tag.
2. list item is a text node, render it to span tag.
3. list item has some nodes, use first node.
4. list item have other nodes(image, table, code-block), don't render.
> not link bug

- seahub/api2/endpoints/repo_history.py
return client_version, device_name, second_parent_id and tags field
> update repo history api

- frontend/src/components/index-viewer.js
- frontend/src/components/toolbar/groups-toolbar.js
- frontend/src/components/wiki-list-view/wiki-list-view.js
- frontend/src/pages/shared-with-all/public-shared-view.js
- frontend/src/pages/wikis/wikis.js
1. fix button align in mobile devices.
2. fix wiki-list-view page icon width.
> button align

- frontend/src/components/review-list-view/review-comments.js
- frontend/src/draft.js
减少界面请求：评论数量、未处理评论数量、评论内容的请求改成一次请求，同时将上面三个变量改成一个变量 commentState。
> decrease comments request

- frontend/src/settings.js
* fixed the "can't scroll" problem
> [user settings] modification for Firefox

- seahub/api2/views.py
> update repo download info api

- seahub/api2/endpoints/repos_batch.py
- seahub/urls.py
- seahub/utils/repo.py
- tests/api/endpoints/test_repos_batch.py
1, add batch delete item api
2, check sub folder permission when batch delte/move item
> update repo batch api

- seahub/api2/endpoints/share_links.py
- seahub/api2/views.py
use SHARE_LINK_EXPIRE_DAYS_DEFAULT
> update share link api

- frontend/src/components/dialog/create-repo-dialog.js
if sys admin set min password length for repo, use that length to show and check password
length in create repo dialog.
> repo with encrypt:

- frontend/src/components/dialog/label-repo-state-dialog.js
- frontend/src/components/dialog/lib-history-setting-dialog.js
- frontend/src/pages/my-libs/mylib-repo-list-item.js
- frontend/src/pages/my-libs/mylib-repo-menu.js
* 'label current state': modified text, added 'cancel' btn for the
dialog, moved the dialog to the top of the page
* 'history setting': moved the dialog to the top of the page
> [my libs] modification for 'label current state' & 'history setting'

- frontend/src/components/shared-repo-list-view/shared-repo-list-item.js
> Revert "repair group menu bug"

- frontend/src/components/dir-view-mode/dir-grid-view.js
- frontend/src/components/dirent-grid-view/dirent-grid-item.js
- frontend/src/components/dirent-grid-view/dirent-grid-view.js
- frontend/src/components/dirent-list-view/dirent-list-item.js
- frontend/src/css/grid-view.css
* modifie UI for 'thumbnail' images
* added 'Tags'('Select Tags') for file
* show tags for tagged files
> [grid] improvement

- frontend/src/components/file-view/file-view.js
- frontend/src/utils/utils.js
* added 'getErrorMsg' to utils.js
> [file view] added 'catch' for requests

- frontend/src/components/libs-mobile-thead.js
- frontend/src/components/shared-repo-list-view/shared-repo-list-item.js
- frontend/src/components/shared-repo-list-view/shared-repo-list-view.js
- frontend/src/pages/groups/group-view.js
- frontend/src/pages/my-libs/mylib-repo-list-view.js
- frontend/src/pages/shared-libs/shared-libs.js
- frontend/src/pages/shared-with-all/public-shared-view.js
* added component libs-mobile-thead.js
> [shared with all, group, groups] mobile: improvement

- frontend/src/css/comments-list.css
> fix FF comment list style

- frontend/src/pages/lib-content-view/lib-content-view.js
- frontend/src/pages/share-admin/folders.js
- frontend/src/pages/share-admin/libraries.js
- frontend/src/pages/share-admin/share-links.js
- frontend/src/pages/share-admin/upload-links.js
- frontend/src/pages/shared-libs/shared-libs.js
- frontend/src/pages/shared-with-all/public-shared-view.js
> Revert "repair translate error"

- frontend/src/components/dialog/perm-select.js
- frontend/src/css/files-activities.css
- frontend/src/models/shared-repo-info.js
- frontend/src/pages/dashboard/files-activities.js
- frontend/src/pages/share-admin/libraries.js
- frontend/src/utils/utils.js
- media/css/seahub_react.css
> [share admin] libraries: added support for mobile

- frontend/src/models/shared-folder-info.js
- frontend/src/pages/share-admin/folders.js
- frontend/src/pages/share-admin/libraries.js
> [share admin] folders: added support for mobile; bugfix & improvement

- frontend/src/components/dialog/generate-upload-link.js
- frontend/src/components/dialog/share-admin-link.js
- frontend/src/models/upload-link.js
- frontend/src/pages/share-admin/share-links.js
- frontend/src/pages/share-admin/upload-links.js
> [share admin] upload links: added support for mobile; improvement

- frontend/src/components/dialog/rename-dirent.js
- frontend/src/components/dirent-grid-view/dirent-grid-view.js
- frontend/src/components/dirent-list-view/dirent-list-view.js
- frontend/src/components/toolbar/multiple-dir-operation-toolbar.js
- frontend/src/pages/lib-content-view/lib-content-toolbar.js
- frontend/src/pages/lib-content-view/lib-content-view.js
- frontend/src/utils/utils.js
* added `getDirentOperationList` to utils.js
* improved code
> [dir view] updated 'top operation list' for current active dirent

- seahub/settings.py
- seahub/two_factor/middleware.py
add setting ENABLE_FORCE_2FA_TO_ALL_USERS
> add setting ENABLE_FORCE_2FA_TO_ALL_USERS

- frontend/src/components/dialog/add-abuse-report-dialog.js
- frontend/src/components/file-uploader/upload-list-item.js
- frontend/src/components/main-side-nav.js
- frontend/src/css/share-link-dialog.css
- frontend/src/pages/my-libs/mylib-repo-list-item.js
- frontend/src/pages/sys-admin/users/user-nav.js
Change share dialog dropdown menu style
> Change share dialog

- seahub/api2/endpoints/admin/organizations.py
> update admin search org api

- frontend/src/components/dialog/sysadmin-dialog/sysadmin-add-user-dialog.js
> Revert "fix add user role in non pro env"

- seahub/templates/base_for_small_panel.html
- seahub/templates/decrypt_repo_form.html
- seahub/templates/share_access_validation.html
> [decrypt page for share links] redesigned it.

- frontend/src/components/copy-to-clipboard.js
- frontend/src/components/dialog/internal-link-dialog.js
- frontend/src/components/dialog/internal-link.js
- frontend/src/components/dialog/org-admin-invite-user-dialog.js
- frontend/src/components/dialog/share-admin-link.js
- frontend/src/components/dialog/view-link-dialog.js
* copy link to the clipboard, and make it shown as a link when pasted
into the seafile markdown editor
> [copy link] improved 'copy link to the clipboard'

- frontend/src/components/main-side-nav.js
- seahub/settings.py
> Revert "add type & lang to custom nav"

- frontend/src/components/dialog/share-to-group.js
- frontend/src/components/dialog/share-to-user.js
when update to 'admin' permission
> fix bug of share to user/group

- frontend/src/components/dialog/lib-sub-folder-permission-dialog.js
- frontend/src/components/dialog/lib-sub-folder-set-group-permission-dialog.js
- frontend/src/components/dialog/lib-sub-folder-set-user-permission-dialog.js
- frontend/src/components/dialog/repo-api-token-dialog.js
- frontend/src/components/dialog/share-dialog.js
- frontend/src/components/dialog/share-to-group.js
- frontend/src/components/dialog/share-to-invite-people.js
- frontend/src/components/dialog/share-to-user.js
- frontend/src/components/dialog/sysadmin-dialog/sysadmin-share-dialog.js
- frontend/src/css/share-link-dialog.css
- media/css/seahub_react.css
* redesigned 'share' dialog and 'folder permission' dialog for mobile
* improved 'API token' dialog
> improved dialogs

- frontend/src/components/wiki-markdown-viewer.js
- frontend/src/utils/utils.js
* only modified links of inserted files from the current library
> [wiki markdown file] modified links in the file content

- seahub/api2/endpoints/admin/share_links.py
- seahub/api2/endpoints/admin/upload_links.py
support 'order_by' and 'direction' parameter
> update admin get share/upload links api

- frontend/src/components/toolbar/dir-operation-toolbar.js
- frontend/src/components/toolbar/multiple-dir-operation-toolbar.js
- frontend/src/css/toolbar.css
- frontend/src/pages/lib-content-view/lib-content-toolbar.js
> Revert "Update menu permission valid"

- frontend/src/components/date-and-time-picker.js
* changed it to 'click outside to close the dialog'
> [share dialog] expiration time: improved 'date-and-time-picker'

- frontend/src/components/date-and-time-picker.js
- frontend/src/pages/search/advanced-search.js
- frontend/src/pages/search/main-panel.js
* fixed UI
* added 'clear', 'disabledDate', 'click outside to close'
* allow user to choose the same day for start & end date
> [advanced search] fixed and improved 'date picker'

- frontend/src/utils/utils.js
* make a member in a department can share a folder in a library of the
department, with internal link
> [share] internal link: fixup for 'folder'

- frontend/src/components/dialog/share-to-user.js
- frontend/src/css/share-to-user.css
- seahub/api2/endpoints/dir_shared_items.py
return contact_email and avatar_url field
> update dir shared item api

- seahub/api2/views.py
pass storage_id args when create enc repo via client
> update create repo api

- media/css/print_for_md_file_view.css
* when the right panel is open, make the print be ok
* print all the pages in Firefox
> [markdown] improved 'print'

- seahub/api2/endpoints/admin/org_repos.py
use group_name as owner_name for group owned repos
> update admin org repos api

- seahub/views/file.py
can only preview file even if locked by me
> update office lock logic

- seahub/api2/endpoints/admin/users.py
remove audit_last_access and update_last_access
> update admin get users api

- seahub/wopi/views.py
add pro version check before lock/unlock file
> update edit file via wopi

- seahub/views/file.py
consider if is locked when determine if can edit
> update view shared file

- frontend/src/components/dirent-detail/dirent-details.js
- frontend/src/components/dirent-detail/file-details.js
- frontend/src/pages/lib-content-view/lib-content-view.js
- frontend/src/pages/starred/starred.js
- frontend/src/shared-dir-view.js
- frontend/src/utils/constants.js
- seahub/templates/base_for_react.html
- seahub/templates/common_file_view_react.html
- seahub/templates/view_shared_dir_react.html
- seahub/views/__init__.py
- seahub/views/file.py
- seahub/views/repo.py
- when 'video thumbnail' feature is enabled, display the thumbnails
for 'dir view', 'starred(favorites)', 'file view', 'shared dir view'
pages.
> [video thumbnail] display the thumbnails for some pages.

- frontend/src/components/select-editor/select-editor.js
> [share dialog] fixed 'permission' problem for 'share to user' & 'share to group'

- seahub/thumbnail/utils.py
This fixed every problem I had regarding video thumbnails. Also works with pretty much any video format.
> Remove moviepy dependency, use ffmpeg for all video thumbnails

- seahub/onlyoffice/views.py
> update onlyoffice callback view

- seahub/onlyoffice/utils.py
Set [user.id](https://api.onlyoffice.com/editors/config/editor#user) to improve the display of data when co-editing.
> onlyoffice-config: editor config userid

- seahub/api2/endpoints/admin/group_libraries.py
use department name as user name when list group repos on admin page
> update admin group libs api

- seahub/base/context_processors.py
- seahub/settings.py
- seahub/templates/base.html
- seahub/templates/base_for_react.html
Which gets used in the html header `<meta name="description" ... />` tag.
> Add SITE_DESCRIPTION config variable

- seahub/role_permissions/settings.py
- seahub/role_permissions/utils.py
if admin role is not a valid role, user audit admin role as default
> update admin role

- seahub/base/middleware.py
- seahub/settings.py
This reverts commit 57e5a289fc5800ef1fc3c7a561fadaac6af44d05.
> Revert "support for SESSION_COOKIE_SAMESITE"

- frontend/src/markdown-editor.js
- frontend/src/shared-file-view-markdown.js
- seahub/views/file.py
> Revert "repair code bug"

- frontend/src/components/dialog/save-shared-dir-dialog.js
- frontend/src/shared-dir-view.js
- seahub/api2/endpoints/share_links.py
show progress when save file/folder in shared folder
> update shared folder

- frontend/src/components/dialog/generate-share-link.js
- frontend/src/components/dialog/generate-upload-link.js
- frontend/src/components/dialog/update-webdav-password.js
- frontend/src/components/user-settings/webdav-password.js
- frontend/src/utils/utils.js
- seahub/api2/endpoints/webdav_secret.py
- seahub/profile/templates/profile/set_profile_react.html
- seahub/profile/views.py
- seahub/settings.py
add WEBDAV_SECRET_MIN_LENGTH and WEBDAV_SECRET_STRENGTH_LEVEL
> update webdav secret

- frontend/src/components/dialog/delete-repo-dialog.js
- seahub/api2/endpoints/repos.py
If there is no library share information, no message is displayed
> update share info message when delete repo

- frontend/src/components/dialog/share-to-group.js
- frontend/src/components/dialog/share-to-user.js
- seahub/api2/endpoints/group_owned_libraries.py
add 'cloud-edit', 'preview' permission
support 'cloud-edit', 'preview' and custom permission when modify share
> update share dept repo

- seahub/templates/shared_file_view_react.html
- seahub/templates/wiki/wiki.html
markdown 外链界面和 wiki 界面中，预览图片的图标修复
> Add seafile editor font for external html

- seahub/thumbnail/utils.py
Fixed PSD image preview as methods in psd_tools has been updated.
https://psd-tools.readthedocs.io/en/latest/migration.html
> Fixed preview PSD images

- seahub/views/file.py
get can_edit and can_download permission for OnlyOffice
> update view file in shared dir

- seahub/views/file.py
on history/trash/snapshot page
> disallow preview office file in encrypted repo

- seahub/api2/endpoints/admin/users.py
return last_access_time and last_login info
> update admin get user info

- seahub/api2/endpoints/share_links.py
- seahub/api2/endpoints/upload_links.py
- seahub/utils/__init__.py
Password can only contain number, upper letter, lower letter and other symbols.
> update password check when create share/upload link

- seahub/institutions/templates/institutions/useradmin.html
- seahub/institutions/templates/institutions/useradmin_search.html
- seahub/institutions/views.py
can't operate system/institution admin
> update institution admin page

- seahub/krb5_auth/settings.template
https://www.iana.org/domains/reserved
> use exampe.com instead of domain.com

- scripts/sqlite2mysql.py
This MR fixes problems of the sqlite2mysql.py toolwith "IF NOT EXISTS" statements and the value of "DEFAULT" statements.
Fixes https://github.com/haiwen/seafile/issues/2505
> Fix sqlite2mysql script problems with seahub_db

- frontend/config/webpack.config.js
- frontend/package-lock.json
- frontend/package.json
- seahub/templates/base_for_react.html
- seahub/templates/markdown_file_view_react.html
> Revert "update webpack bundle version"

- seahub/profile/views.py
- seahub/views/sso.py
NOT how two_factor_auth on sso user's profile page
> two_factor_auth

- seahub/api2/endpoints/share_links.py
return repo_folder_permission field for update share link permission
> update get share link(s) api

- frontend/src/components/dirent-grid-view/dirent-grid-view.js
- frontend/src/components/dirent-list-view/dirent-list-item.js
- frontend/src/components/toolbar/multiple-dir-operation-toolbar.js
- frontend/src/components/toolbar/view-mode-toolbar.js
- frontend/src/utils/text-translation.js
- frontend/src/utils/utils.js
'more' dropdown menus in <tr> & the top toolbar
- click 'Properties', the 'info' panel will be shown
> [dir view] for file items: added 'Properties' to its context menu,

- frontend/src/components/select-editor/select-editor.js
- frontend/src/components/select-editor/share-permission-editor.js
- frontend/src/models/shared-folder-info.js
- frontend/src/models/shared-repo-info.js
- frontend/src/pages/share-admin/folders.js
- frontend/src/pages/share-admin/libraries.js
- seahub/api2/endpoints/shared_folders.py
- seahub/api2/endpoints/shared_repos.py
return custom_permission_name field
> update get shared repos/folders

- seahub/api2/endpoints/multi_share_links.py
- seahub/api2/endpoints/share_links.py
- seahub/constants.py
- seahub/share/decorators.py
- seahub/share/models.py
check if share link count exceeds limit
> update create share link api

- frontend/src/pages/org-admin/org-user-item.js
- frontend/src/pages/org-admin/org-users-admins.js
- frontend/src/pages/org-admin/org-users-search-users.js
- frontend/src/pages/org-admin/org-users-users.js
- frontend/src/pages/sys-admin/users/search-users.js
- frontend/src/pages/sys-admin/users/users-content.js
- frontend/src/pages/sys-admin/users/users.js
- seahub/base/templatetags/seahub_tags.py
use "Successfully deleted 1 item"
> update org admin delete user msg

- frontend/src/components/dirent-list-view/dirent-list-item.js
fix bug caused by https://github.com/haiwen/seahub/pull/5672/
> fix tag list ID bug

- frontend/src/components/dirent-list-view/dirent-list-item.js
> Revert "fix tag list ID bug"

- seahub/api2/endpoints/admin/users.py
not show password if successfully send email to user
> update admin reset user password tip

- seahub/api2/endpoints/group_members.py
> update error msg when import group members

- seahub/api2/endpoints/group_libraries.py
do not check repo custom share permission
> update create group library api

- seahub/api2/endpoints/custom_share_permissions.py
check if permission belongs to repo
> update repo custom share permission api

- seahub/api2/views.py
> update get repo info api

- seahub/api2/views.py
> update share repo to dept

- frontend/src/pages/lib-content-view/lib-content-view.js
- seahub/api2/endpoints/file.py
show detailed msg when failed to rename file because file is locked
> update rename file error msg

- frontend/src/components/dialog/create-repo-dialog.js
- frontend/src/components/dialog/lib-sub-folder-set-group-permission-dialog.js
- frontend/src/components/dialog/transfer-dialog.js
- frontend/src/components/select-editor/repo-api-token-permission-editor.js
- frontend/src/components/user-select.js
Fix some no value select components.
> Fix select UI

- seahub/api2/endpoints/file.py
can freeze document even if file is locked by OnlineOffice
> update lock file api

- seahub/views/file.py
check if is pro when get lock info
> update sdoc is freezed

- seahub/api2/endpoints/via_repo_token.py
- seahub/urls.py
https://github.com/rclone/rclone/issues/6126﻿﻿
﻿https://github.com/haiwen/seahub/issues/5717
> Feat opt with repo

- frontend/src/components/sdoc-wiki-page-viewer/style.css
- frontend/src/components/search/ai-search-ask.js
- frontend/src/css/lib-content-view.css
- frontend/src/css/side-panel.css
- frontend/src/pages/wiki/wiki.css
fix ai-search bug caused by https://github.com/haiwen/seahub/pull/5888
> fix ai-search loading bug

- seahub/api2/views.py
- seahub/utils/__init__.py
> update create repo

- seahub/api2/endpoints/upload_links.py
- seahub/views/repo.py
check folder's permission instead of repo permission
> update upload link permission check

- frontend/src/pages/upload-link/file-uploader.js
- frontend/src/pages/upload-link/upload-progress-dialog.js
- handled eage cases: 'out of quota' happens when a file is being uploaded or before the uploading
> ['upload link' page] fixup & improvement for 'file upload'

- frontend/src/components/common/notice-item.js
- seahub/notifications/models.py
A file named {filename} is uploaded.
A folder named {foldername} is uploaded.
> update notice when file/folder is uploaded

- seahub/api2/endpoints/admin/device_errors.py
- seahub/utils/db_api.py
> client error log improvement

- frontend/src/components/dir-view-mode/dir-column-view.js
- frontend/src/components/toolbar/view-mode-toolbar.js
- frontend/src/pages/lib-content-view/lib-content-container.js
- frontend/src/pages/lib-content-view/lib-content-view.js
the left side 'tree' panel; let the 'list' & 'grid' column mode icon only control the right side main content
> [dir view] redesigned it: removed the 'column' mode icon; always display

- frontend/src/pages/libraries/index.js
> 12.0 change libraries page loading icon

- frontend/src/components/operations/style.css
- frontend/src/components/wiki-card-view/wiki-card-group.js
- frontend/src/components/wiki-card-view/wiki-card-item.js
- frontend/src/components/wiki-card-view/wiki-card-view.css
- frontend/src/components/wiki-card-view/wiki-card-view.js
- frontend/src/css/dirent-detail.css
- frontend/src/css/file-uploader.css
- frontend/src/css/files-activities.css
- frontend/src/css/grid-view.css
- frontend/src/css/image-file-view.css
- frontend/src/css/layout.css
- frontend/src/css/notification.css
- frontend/src/css/repo-info-bar.css
- frontend/src/css/repo-seatable-integration-dialog.css
- frontend/src/css/search.css
- frontend/src/css/system-info.css
- frontend/src/css/system-stat.css
- frontend/src/css/user-notifications.css
- frontend/src/css/user-settings.css
- frontend/src/pages/markdown-editor/css/detail-list-view.css
- frontend/src/pages/sdoc/sdoc-file-history/index.css
- media/css/seahub.css
- media/css/seahub_react.css
1、change Wiki page style
2、change font color #333333 and #332222 to #212529
3、change border-color #e8e8e8 to #eee
> change Wiki style

- frontend/src/components/dirent-list-view/dirent-list-item.js
- frontend/src/components/user-settings/linked-devices.js
- frontend/src/pages/invitations/invitations-view.js
- frontend/src/pages/linked-devices/linked-devices.js
- frontend/src/pages/share-admin/folders.js
- frontend/src/pages/share-admin/libraries.js
- frontend/src/pages/share-admin/share-links.js
- frontend/src/pages/share-admin/upload-links.js
- frontend/src/pages/shared-libs/shared-libs.js
- frontend/src/pages/starred/starred.js
Refactor these pages,  do not run mobile functions on PC devices
- dirent-list-item
- share-admin-upload-links
- share-admin-share-links
- share-admin: folders
- share-admin: libraries
- shared-libs
- linked-devices
- linked-devices(in user-settings page)
- invitations
- starred
> [Refactor] Do not run mobile functions on PC devices

- frontend/src/components/dialog/share-to-group.js
- frontend/src/components/dialog/share-to-user.js
- frontend/src/components/dialog/share-wiki-dialog.js
- frontend/src/components/select-editor/select-editor.js
- frontend/src/components/select-editor/share-permission-editor.js
- frontend/src/components/wiki-card-view/wiki-card-group.js
- frontend/src/components/wiki-card-view/wiki-card-item.js
- frontend/src/components/wiki-card-view/wiki-card-view.js
- frontend/src/pages/wikis/wikis.js
- seahub/api2/endpoints/repos.py
- seahub/api2/endpoints/wiki2.py
- seahub/utils/ccnet_db.py
- seahub/wiki2/utils.py
- seahub/wiki2/views.py
update leave and return
update get group info
> share wiki

- frontend/src/components/dialog/my-deleted-repos.js
- frontend/src/components/empty-tip.js
- frontend/src/css/my-deleted-repos.css
- frontend/src/pages/my-libs/my-libs.js
* moved the entrance from the right corner to the left dropdown menu of 'My Libraries' page
* redesigned it: changed it from an independent page to a dialog
> [my deleted libraries] redesigned it

- frontend/src/components/dialog/trash-dialog.js
- frontend/src/components/dropdown-menu/item-dropdown-menu.js
- frontend/src/components/tree-section/index.js
- frontend/src/components/tree-view/tree-node-view.js
- frontend/src/css/trash-dialog.css
- frontend/src/metadata/metadata-tree-view/view-item/index.js
- frontend/src/user-notifications.js
01 notification more icon
02 change mobile trash dialog
03 metadata mobile menu
> change mobile style

- frontend/src/components/context-menu/context-menu.js
- frontend/src/components/dropdown-menu/item-dropdown-menu.js
- frontend/src/utils/text-translation.js
- frontend/src/utils/utils.js
make 'convert to markdown', 'convert to docx', 'export as docx' as its sub-menu options
- menus: the 'more operation' menu for the current `<tr>`, the 'more operation' menu for the single selected file, the context menu
> ['dir view'] for 'sdoc' file: add menu option 'Convert & Export', and

- frontend/src/css/empty-tip.css
- frontend/src/css/file-history.css
- frontend/src/css/file-view.css
- frontend/src/css/files.css
- frontend/src/css/icon.css
- frontend/src/css/image-file-view.css
- frontend/src/css/layout.css
- frontend/src/css/pdf-file-view.css
- frontend/src/css/spreadsheet-file-view.css
- frontend/src/css/subscription.css
- frontend/src/css/svg-file-view.css
- frontend/src/css/system-admin-web-settings.css
- frontend/src/css/system-notification.css
- frontend/src/css/text-file-view.css
- frontend/src/css/tip-for-new-file.css
- frontend/src/css/transfer-dialog.css
- frontend/src/css/tree-view-contextmenu.css
- frontend/src/metadata/metadata-view/components/detail-editor/checkbox-editor/index.css
- frontend/src/pages/wikis/wikis.js
> change empty tip title margin

- frontend/src/css/search.css
Search mask z-index should higher than side nav z-index
> change search mask index

- frontend/src/components/context-menu/context-menu.js
- frontend/src/components/dropdown-menu/item-dropdown-menu.js
- frontend/src/css/item-dropdown-menu.css
'Display files' in the file tree panel
* fixup for sdoc: when hover the other menu options in the first-level menu, hide the sub-menu
* for 'Display files': refactored the memu option and removed the bad effect on the other menus & menu options
> ['dir view'] fixup for sdoc's 'sub-menu'; fixup & improvement for the

- frontend/src/components/dir-view-mode/dir-column-file.css
> change seafile-markdown-viewer-modal-header style

- frontend/src/pages/starred/starred.js
- display '--' instead of 'Invalid date' for deleted items
- improved 'unstar' in desktop; fixup for 'unstar' in mobile
- display 'deleted' text tip for deleted items in mobile
> ['Favorites'] fixup & improvements

- frontend/src/assets/icons/more-level.svg
- frontend/src/components/search/search.js
- frontend/src/css/search.css
dialog & a possile 'More' link)
- display at most 20 search result items in the dialog
- if there are more than 20 result items, display a 'More' link in the bottom of the dialog. click the link, an independent search result page will be shown, with all the search parameters kept.
> [search] fixup & improvement(display at most 20 result items in the

- seahub/views/file.py
> update view file via shared dir

- frontend/src/components/file-view/file-toolbar.js
hide print button if can not download
> update view pdf file page

- seahub/api2/endpoints/search_user.py
- seahub/settings.py
- seahub/utils/ccnet_db.py
- seahub/utils/db_api.py
- tests/api/endpoints/test_search_user.py
- tests/api/models/test_token_v2.py
> update search user web api

- frontend/src/pages/wiki2/index.js
fix mobile wiki side panel bug caused by https://github.com/haiwen/seahub/pull/7006
> fix mobile wiki close side panel

- seahub/dingtalk/views.py
- seahub/weixin/views.py
- seahub/work_weixin/views.py
> update weixin/work_weixin/dingtalk sso

- frontend/src/pages/wiki2/wiki-right-header/page-title-editor.js
- frontend/src/pages/wiki2/wiki-right-header/page-title.js
> [wiki] fixup for 'published wiki pages rendered as blank pages'

- seahub/api2/endpoints/internal_api.py
- seahub/role_permissions/settings.py
- seahub/urls.py
- seahub/utils/file_size.py
- tests/seahub/role_permissions/test_utils.py
> Revert "Download rate limit"

- frontend/package-lock.json
- frontend/package.json
> Revert "debug: metadata ui beta version"

- frontend/src/components/shared-repo-list-view/shared-repo-list-item.js
- frontend/src/pages/org-admin/libraries/org-all-repos.js
- frontend/src/pages/sys-admin/repos/repos.js
- frontend/src/pages/sys-admin/users/user-repos.js
fix bugs caused by https://github.com/haiwen/seahub/pull/7183/
> fix transfer repos func name

- seahub/adfs_auth/views.py
fix login failed as soon as license limit is reached
> update saml login

- frontend/src/components/org-admin-group-nav.js
- frontend/src/translate.js
fix use 'django-admin makemessages' can not get string 'Group info'
> fix 'Group info' text

- seahub/adfs_auth/views.py
user "The number of users exceeds the limit."
> update adfs user login error msg

- frontend/src/components/toolbar/single-dropdown-toolbar.js
- frontend/src/css/single-dropdown-toolbar.css
- frontend/src/pages/groups/group-item.js
- frontend/src/pages/groups/group-view.js
- frontend/src/pages/libraries/index.js
- frontend/src/pages/my-libs/my-libs.js
- frontend/src/pages/shared-with-all/index.js
> Revert "Revert "[library list] added 'plus' icon to the toggle of the dropdown menus …""

- seahub/views/file.py
fix bug caused by https://github.com/haiwen/seahub/pull/7554
> fix bug in external view image

- tests/seahub/repo_metadata/test_view.py
update test view
update load md
> add md test

- frontend/src/pages/share-admin/share-links.js
In the early stages of interaction, the backend paginated the link list and the frontend implemented sorting. If there are too many links, scrolling to bottom then load more links and reordering the page will cause the existing links to be out of order, affecting the user experience. Therefore, this change has removed the frontend sorting.
> [12.0] remove frontend sort link in share links page

- frontend/src/css/log-filter.css
- frontend/src/pages/dashboard/files-activities.js
- frontend/src/pages/dashboard/log-repo-selector.js
- frontend/src/pages/dashboard/log-user-selector.js
- frontend/src/pages/org-admin/org-logs-file-transfer.js
- frontend/src/pages/org-admin/org-logs-group-member-audit.js
- frontend/src/pages/org-admin/web-settings/web-settings.js
FIX: https://github.com/haiwen/seahub/pull/7669 change system admin log page style, but have an effect on file activities page.
> fix activity page scroll and css format

- frontend/src/components/dialog/org-set-group-quota-dialog.js
- frontend/src/components/dialog/sysadmin-dialog/sysadmin-set-group-quota-dialog.js
- frontend/src/pages/org-admin/departments/department-node.js
- frontend/src/pages/org-admin/departments/department.js
- frontend/src/pages/org-admin/departments/departments-node-dropdown-menu.js
- frontend/src/pages/org-admin/departments/departments-tree-panel.js
- frontend/src/pages/org-admin/departments/departments.js
- frontend/src/pages/org-admin/departments/tree-node.js
- frontend/src/pages/sys-admin/departments/department-node.js
- frontend/src/pages/sys-admin/departments/department.js
- frontend/src/pages/sys-admin/departments/departments-node-dropdown-menu.js
- frontend/src/pages/sys-admin/departments/departments-tree-panel.js
- frontend/src/pages/sys-admin/departments/departments.js
- frontend/src/pages/sys-admin/departments/tree-node.js
Reference：
change old department UI to new UI：https://github.com/haiwen/seahub/pull/7010/ 
refactor department：https://github.com/haiwen/seahub/pull/7350
> 12.0 department set quota

- scripts/reset-admin.sh
- scripts/run_index_master.sh
- scripts/run_index_worker.sh
- scripts/seafile-background-tasks.sh
- scripts/seahub.sh
A minor bug but should fix the typo or remove the condition. At the moment it is useless.
> fix typo in seahub scripts

- frontend/src/components/dialog/image-dialog/index.css
- frontend/src/components/dirent-detail/detail-item/index.css
- frontend/src/components/dirent-detail/detail-item/index.js
- frontend/src/components/dirent-detail/detail/detail/index.js
- frontend/src/components/dirent-detail/dirent-details/file-details/collapse/index.css
- frontend/src/components/dirent-detail/dirent-details/file-details/index.css
- frontend/src/components/dirent-detail/dirent-details/index.css
- frontend/src/components/dirent-detail/embedded-file-details/index.js
- frontend/src/metadata/components/cell-formatter/file-tags/index.css
- frontend/src/metadata/components/detail-editor/checkbox-editor/index.css
- frontend/src/metadata/components/detail-editor/collaborator-editor/index.css
- frontend/src/metadata/components/detail-editor/date-editor/index.css
- frontend/src/metadata/components/detail-editor/index.css
- frontend/src/metadata/components/detail-editor/long-text-editor/index.css
- frontend/src/metadata/components/detail-editor/rate-editor/index.css
- frontend/src/metadata/components/detail-editor/single-select-editor/index.css
- frontend/src/metadata/components/detail-editor/tags-editor/index.css
- frontend/src/metadata/components/metadata-details/index.css
> Revert "Optimize/details"

- frontend/src/components/dirent-list-view/dirent-list-item.js
- frontend/src/pages/wiki2/wiki-comment/plugin-item.js
fix bug caused by https://github.com/haiwen/seahub/pull/7776
> fix list mode star file bug

- frontend/src/components/toolbar/dir-operation-toolbar.js
fix create mobile file or folder bug caused by https://github.com/haiwen/seahub/pull/7923/
> fix mobile create file or folder bug

- frontend/src/view-file-collabora-online.js
- seahub/templates/view_file_wopi.html
Added  `allow="clipboard-read *; clipboard-write *"` to iframe as recommended by Collabora docs: https://sdk.collaboraonline.com/docs/advanced_integration.html#clipboard-handling
> Collabora: Fix clipboard issue. Fixes #8209
